apiVersion: v1
kind: Pod
metadata:
  name: liveness
  labels:
    app: example
spec:
  containers:
    - name: my-web-app
      image: doramar97/my-web-app:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 2
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 10
