apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "2"         # Limit CPU requests to 2 cores
    requests.memory: 4Gi      # Limit memory requests to 4GiB
    limits.cpu: "4"           # Limit total CPU usage to 4 cores
    limits.memory: 8Gi        # Limit total memory usage to 8GiB
    pods: "10"                # Max number of pods allowed in this namespace