apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: bfhsdbhiasdbf
spec:
  replicas: 2 # Create 2 pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        env: dev
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.19 # NGINX image
          ports:
            - containerPort: 80 # Expose port 80
