apiVersion: v1
kind: Pod
metadata:
  name: python-app
spec:
  containers:
  - name: python-container
    image: doramar97/my-web-app:latest  # Use your Docker image
    env:
    - name: APP_NAME
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_NAME
    - name: APP_PORT
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: APP_PORT
  restartPolicy: Never

