apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-secret-file
spec:
  containers:
  - name: myapp-container
    image: nginx
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets
  volumes:
  - name: secret-volume
    secret:
      secretName: db-secret

