apiVersion: v1
kind: Pod
metadata:
  name: resource-limits-example
spec:
  containers:
    - name: resource-container
      image: nginx
      resources:
        requests:
          memory: "5Mi" # Request 64Mi of memory
          cpu: "250m" # Request 250 milliCPU (0.25 CPU)
        limits:
          memory: "10Mi" # Limit memory to 128Mi
          cpu: "500m" # Limit CPU to 500 milliCPU (0.5 CPU)

