apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
spec:
  containers:
  - name: myapp-container
    image: nginx
    env:
    - name: APP_NAME
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: appName
    - name: APP_PORT
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: appPort

