apiVersion: v1
kind: Pod
metadata:
  name: development
spec:
  containers:
  - name: myapp-container
    image: nginx
    env:
    - name: CPU
      valueFrom:
        configMapKeyRef:
          name: my-config-development # From what confingMap get the values ?
          key: APP_NAME # What Value to put in to APP_NAME
    - name: APP_PORT
      valueFrom:
        configMapKeyRef:
          name: my-config
          key: APP_PORT

